graph LR
  v2.1.unbound.dns.delete -->|next| v2.2.paloalto.rule.delete
  v2.1.unbound.dns.delete -->|error| v2.organization.delete
  v2.2.paloalto.rule.delete -->|next| v2.3.paloalto.nat.delete
  v2.2.paloalto.rule.delete -->|error| v2.organization.delete
  v2.3.paloalto.nat.delete -->|next| v2.4.paloalto.host.delete
  v2.3.paloalto.nat.delete -->|error| v2.organization.delete
  v2.4.paloalto.host.delete -->|next| v2.5.paloalto.tag.delete
  v2.4.paloalto.host.delete -->|error| v2.organization.delete
  v2.5.paloalto.tag.delete -->|next| v2.6.nsxt.vs.delete
  v2.5.paloalto.tag.delete -->|error| v2.organization.delete
  v2.6.nsxt.vs.delete -->|next| v2.7.nsxt.pool.delete
  v2.6.nsxt.vs.delete -->|error| v2.organization.delete
  v2.7.nsxt.pool.delete -->|next| v2.8.nsxt.lb.delete
  v2.7.nsxt.pool.delete -->|error| v2.organization.delete
  v2.8.nsxt.lb.delete -->|next| v2.9.vsphere.snapshot.delete
  v2.8.nsxt.lb.delete -->|error| v2.organization.delete
  v2.9.vsphere.snapshot.delete -->|next| v2.10.vsphere.disk.detach
  v2.9.vsphere.snapshot.delete -->|error| v2.organization.delete
  v2.10.vsphere.disk.detach -->|next| v2.11.vsphere.disk.delete
  v2.10.vsphere.disk.detach -->|error| v2.organization.delete
  v2.11.vsphere.disk.delete -->|next| v2.12.vsphere.vm.delete
  v2.11.vsphere.disk.delete -->|error| v2.organization.delete
  v2.12.vsphere.vm.delete -->|next| v2.13.nsxt.nat.delete
  v2.12.vsphere.vm.delete -->|error| v2.organization.delete
  v2.13.nsxt.nat.delete -->|next| v2.14.nsxt.policy.delete
  v2.13.nsxt.nat.delete -->|error| v2.organization.delete
  v2.14.nsxt.policy.delete -->|next| v2.15.nsxt.group.delete
  v2.14.nsxt.policy.delete -->|error| v2.organization.delete
  v2.15.nsxt.group.delete -->|next| v2.16.nsxt.segment.profile.delete
  v2.15.nsxt.group.delete -->|error| v2.organization.delete
  v2.16.nsxt.segment.profile.delete -->|next| v2.17.nsxt.segment.delete
  v2.16.nsxt.segment.profile.delete -->|error| v2.organization.delete
  v2.17.nsxt.segment.delete -->|next| v2.18.nsxt.locale.service.delete
  v2.17.nsxt.segment.delete -->|error| v2.organization.delete
  v2.18.nsxt.locale.service.delete -->|next| v2.19.nsxt.tier1.delete
  v2.18.nsxt.locale.service.delete -->|error| v2.organization.delete
  v2.19.nsxt.tier1.delete -->|next| v2.20.vsphere.delete.folder
  v2.19.nsxt.tier1.delete -->|error| v2.organization.delete
  v2.20.vsphere.delete.folder -->|next| v2.organization.delete
  v2.20.vsphere.delete.folder -->|error| v2.organization.delete
