graph LR
  v2.1.rubrik.vm.export -->|next| v2.2.rubrik.vm.check
  v2.1.rubrik.vm.export -->|error| v2.export
  v2.2.rubrik.vm.check -->|next| v2.3.vsphere.vm.info
  v2.2.rubrik.vm.check -->|error| v2.2.vsphere.vm.reconfigure.error.delete
  v2.3.vsphere.vm.info -->|next| v2.4.vsphere.vm.reconfigure
  v2.3.vsphere.vm.info -->|error| v2.2.vsphere.vm.reconfigure.error.delete
  v2.4.vsphere.vm.reconfigure -->|next| v2.5.vsphere.vm.movedisk
  v2.4.vsphere.vm.reconfigure -->|error| v2.2.vsphere.vm.reconfigure.error.delete
  v2.5.vsphere.vm.movedisk -->|next| v2.6.vsphere.vm.userdata
  v2.5.vsphere.vm.movedisk -->|error| v2.2.vsphere.vm.reconfigure.error.delete
  v2.6.vsphere.vm.userdata -->|next| v2.7.nsxt.nat.create
  v2.6.vsphere.vm.userdata -->|error| v2.2.vsphere.vm.reconfigure.error.delete
  v2.7.nsxt.nat.create -->|next| v2.8.nsxt.tag.create
  v2.7.nsxt.nat.create -->|error| v2.1.nsxt.nat.create.error.delete
  v2.8.nsxt.tag.create -->|next| v2.export
  v2.8.nsxt.tag.create -->|error| v2.1.nsxt.nat.create.error.delete
  v2.1.nsxt.nat.create.error.delete -->|next| v2.2.vsphere.vm.reconfigure.error.delete
  v2.1.nsxt.nat.create.error.delete -->|error| v2.export
  v2.2.vsphere.vm.reconfigure.error.delete -->|next| v2.export
  v2.2.vsphere.vm.reconfigure.error.delete -->|error| v2.export
