graph LR
  v2.1.nsxt.vpn.session.delete -->|next| v2.2.nsxt.vpn.endpoint.delete
  v2.1.nsxt.vpn.session.delete -->|error| v2.vpn.delete
  v2.2.nsxt.vpn.endpoint.delete -->|next| v2.3.nsxt.vpn.service.delete
  v2.2.nsxt.vpn.endpoint.delete -->|error| v2.vpn.delete
  v2.3.nsxt.vpn.service.delete -->|next| v2.4.paloalto.rule.edit
  v2.3.nsxt.vpn.service.delete -->|error| v2.vpn.delete
  v2.4.paloalto.rule.edit -->|next| v2.5.paloalto.rule.delete
  v2.4.paloalto.rule.edit -->|error| v2.vpn.delete
  v2.5.paloalto.rule.delete -->|next| v2.6.paloalto.host.delete
  v2.5.paloalto.rule.delete -->|error| v2.vpn.delete
  v2.6.paloalto.host.delete -->|next| v2.7.paloalto.router.edit
  v2.6.paloalto.host.delete -->|error| v2.vpn.delete
  v2.7.paloalto.router.edit -->|next| v2.8.fortinet.vip.delete
  v2.7.paloalto.router.edit -->|error| v2.1.paloalto.rule.create.error.delete
  v2.8.fortinet.vip.delete -->|next| v2.9.fortinet.snat.edit
  v2.8.fortinet.vip.delete -->|error| v2.vpn.delete
  v2.9.fortinet.snat.edit -->|next| v2.10.fortinet.snat.delete
  v2.9.fortinet.snat.edit -->|error| v2.vpn.delete
  v2.10.fortinet.snat.delete -->|next| v2.11.fortinet.ippool.delete
  v2.10.fortinet.snat.delete -->|error| v2.vpn.delete
  v2.11.fortinet.ippool.delete -->|next| v2.vpn.delete
  v2.11.fortinet.ippool.delete -->|error| v2.vpn.delete
