graph LR
  v2.1.paloalto.service.create -->|next| v2.2.paloalto.host.create
  v2.1.paloalto.service.create -->|error| v2.unat.edit
  v2.2.paloalto.host.create -->|next| v2.3.paloalto.unat.delete
  v2.2.paloalto.host.create -->|error| v2.unat.edit
  v2.3.paloalto.unat.delete -->|next| v2.4.paloalto.unat.create
  v2.3.paloalto.unat.delete -->|error| v2.unat.edit
  v2.4.paloalto.unat.create -->|next| v2.5.paloalto.unat.edit
  v2.4.paloalto.unat.create -->|error| v2.unat.edit
  v2.5.paloalto.unat.edit -->|next| v2.6.paloalto.host.delete
  v2.5.paloalto.unat.edit -->|error| v2.unat.edit
  v2.6.paloalto.host.delete -->|next| v2.7.fortinet.address.create
  v2.6.paloalto.host.delete -->|error| v2.unat.edit
  v2.7.fortinet.address.create -->|next| v2.8.fortinet.address.delete
  v2.7.fortinet.address.create -->|error| v2.unat.edit
  v2.8.fortinet.address.delete -->|next| v2.9.fortinet.service.create
  v2.8.fortinet.address.delete -->|error| v2.unat.edit
  v2.9.fortinet.service.create -->|next| v2.10.fortinet.service.delete
  v2.9.fortinet.service.create -->|error| v2.unat.edit
  v2.10.fortinet.service.delete -->|next| v2.11.fortinet.vip.create
  v2.10.fortinet.service.delete -->|error| v2.unat.edit
  v2.11.fortinet.vip.create -->|next| v2.12.fortinet.vip.delete
  v2.11.fortinet.vip.create -->|error| v2.unat.edit
  v2.12.fortinet.vip.delete -->|next| v2.13.fortinet.policy.create
  v2.12.fortinet.vip.delete -->|error| v2.unat.edit
  v2.13.fortinet.policy.create -->|next| v2.14.fortinet.policy.delete
  v2.13.fortinet.policy.create -->|error| v2.unat.edit
  v2.14.fortinet.policy.delete -->|next| v2.unat.edit
  v2.14.fortinet.policy.delete -->|error| v2.unat.edit
