graph LR
  v2.1.vsphere.vm.replicate -->|next| v2.2.vsphere.vm.userdata
  v2.1.vsphere.vm.replicate -->|error| v2.1.vsphere.vm.replicate.error.delete
  v2.2.vsphere.vm.userdata -->|next| v2.3.vsphere.vm.state
  v2.2.vsphere.vm.userdata -->|error| v2.1.vsphere.vm.replicate.error.delete
  v2.3.vsphere.vm.state -->|next| v2.4.nsxt.nat.create
  v2.3.vsphere.vm.state -->|error| v2.virtual.machine.replicate
  v2.4.nsxt.nat.create -->|next| v2.5.nsxt.tag.create
  v2.4.nsxt.nat.create -->|error| v2.1.nsxt.nat.create.error.delete
  v2.5.nsxt.tag.create -->|next| v2.virtual.machine.replicate
  v2.5.nsxt.tag.create -->|error| v2.1.nsxt.nat.create.error.delete
  v2.1.nsxt.nat.create.error.delete -->|next| v2.3.vsphere.vm.state.error.delete
  v2.1.nsxt.nat.create.error.delete -->|error| v2.virtual.machine.replicate
  v2.1.vsphere.vm.replicate.error.delete -->|next| v2.virtual.machine.replicate
  v2.1.vsphere.vm.replicate.error.delete -->|error| v2.virtual.machine.replicate
  v2.3.vsphere.vm.userdata.error.delete -->|next| v2.1.vsphere.vm.replicate.error.delete
  v2.3.vsphere.vm.userdata.error.delete -->|error| v2.virtual.machine.replicate
