graph LR
  v2.1.nsxt.pool.edit -->|next| v2.2.nsxt.vs.edit
  v2.1.nsxt.pool.edit -->|error| v2.virtualserver.edit
  v2.2.nsxt.vs.edit -->|next| v2.3.nsxt.service.create
  v2.2.nsxt.vs.edit -->|error| v2.virtualserver.edit
  v2.3.nsxt.service.create -->|next| v2.4.nsxt.group.create
  v2.3.nsxt.service.create -->|error| v2.virtualserver.edit
  v2.4.nsxt.group.create -->|next| v2.5.nsxt.rule.edit
  v2.4.nsxt.group.create -->|error| v2.virtualserver.edit
  v2.5.nsxt.rule.edit -->|next| v2.virtualserver.edit
  v2.5.nsxt.rule.edit -->|error| v2.virtualserver.edit
