graph LR
  v2.1.paloalto.rule.delete -->|next| v2.2.paloalto.nat.delete
  v2.1.paloalto.rule.delete -->|error| v2.vpn.delete
  v2.2.paloalto.nat.delete -->|next| v2.3.paloalto.host.edit
  v2.2.paloalto.nat.delete -->|error| v2.vpn.delete
  v2.3.paloalto.host.edit -->|next| v2.4.paloalto.host.delete
  v2.3.paloalto.host.edit -->|error| v2.vpn.delete
  v2.4.paloalto.host.delete -->|next| v2.5.nsxt.vs.delete
  v2.4.paloalto.host.delete -->|error| v2.vpn.delete
  v2.5.fortinet.vip.delete -->|next| v2.6.fortinet.snat.delete
  v2.5.fortinet.vip.delete -->|error| v2.vpn.delete
  v2.5.nsxt.vs.delete -->|next| v2.6.nsxt.pool.delete
  v2.5.nsxt.vs.delete -->|error| v2.vpn.delete
  v2.6.fortinet.snat.delete -->|next| v2.7.fortinet.ippool.delete
  v2.6.fortinet.snat.delete -->|error| v2.vpn.delete
  v2.6.nsxt.pool.delete -->|next| v2.7.paloalto.pbf.delete
  v2.6.nsxt.pool.delete -->|error| v2.vpn.delete
  v2.7.fortinet.ippool.delete -->|next| v2.8.nsxt.vs.delete
  v2.7.fortinet.ippool.delete -->|error| v2.vpn.delete
  v2.7.paloalto.pbf.delete -->|next| v2.8.paloalto.ipsec.edit
  v2.7.paloalto.pbf.delete -->|error| v2.vpn.create
  v2.8.paloalto.ipsec.edit -->|next| v2.9.paloalto.ipsec.delete
  v2.8.paloalto.ipsec.edit -->|error| v2.vpn.delete
  v2.9.paloalto.ipsec.delete -->|next| v2.10.paloalto.router.edit
  v2.9.paloalto.ipsec.delete -->|error| v2.vpn.delete
  v2.10.paloalto.router.edit -->|next| v2.11.paloalto.zone.edit
  v2.10.paloalto.router.edit -->|error| v2.vpn.delete
  v2.11.paloalto.zone.edit -->|next| v2.12.paloalto.tunnel.edit
  v2.11.paloalto.zone.edit -->|error| v2.vpn.delete
  v2.12.paloalto.tunnel.edit -->|next| v2.13.paloalto.tunnel.delete
  v2.12.paloalto.tunnel.edit -->|error| v2.vpn.delete
  v2.13.paloalto.tunnel.delete -->|next| v2.14.paloalto.ike.delete
  v2.13.paloalto.tunnel.delete -->|error| v2.vpn.delete
  v2.14.paloalto.ike.delete -->|next| v2.vpn.delete
  v2.14.paloalto.ike.delete -->|error| v2.vpn.delete
