graph LR
  v2.1.paloalto.rule.delete -->|next| v2.2.paloalto.rule.edit
  v2.1.paloalto.rule.delete -->|error| v2.vpn.address.delete
  v2.2.paloalto.rule.edit -->|next| v2.3.paloalto.nat.delete
  v2.2.paloalto.rule.edit -->|error| v2.vpn.address.delete
  v2.3.paloalto.nat.delete -->|next| v2.4.paloalto.nat.edit
  v2.3.paloalto.nat.delete -->|error| v2.vpn.address.delete
  v2.4.paloalto.nat.edit -->|next| v2.5.paloalto.host.delete
  v2.4.paloalto.nat.edit -->|error| v2.vpn.address.delete
  v2.5.paloalto.host.delete -->|next| v2.6.nsxt.lb.edit
  v2.5.paloalto.host.delete -->|error| v2.vpn.address.delete
  v2.6.nsxt.lb.edit -->|next| v2.7.nsxt.vs.delete
  v2.6.nsxt.lb.edit -->|error| v2.vpn.address.delete
  v2.7.nsxt.vs.delete -->|next| v2.8.nsxt.pool.delete
  v2.7.nsxt.vs.delete -->|error| v2.vpn.address.delete
  v2.8.nsxt.pool.delete -->|next| v2.vpn.address.delete
  v2.8.nsxt.pool.delete -->|error| v2.vpn.address.delete
