graph LR
  v2.1.nsxt.vpnsprofile.create -->|next| v2.vpnsprofile.create
  v2.1.nsxt.vpnsprofile.create -->|error| v2.2.nsxt.vpnsprofile.create.error.delete
  v2.2.nsxt.vpnsprofile.create.error.delete -->|next| v2.vpnsprofile.create
  v2.2.nsxt.vpnsprofile.create.error.delete -->|error| v2.vpnsprofile.create
